### ISSUE TITLE
Request: Better Collection/object browser?

### ISSUE THREAD

**Issue by Pat-a-wan** [PlasmaEngine/PlasmaEngine#108]
From the get go using the objects browser is a little bit painful having to scroll drag objects around. Coming from Blender the collections is really nice, maybe something to reference! 

Essentially being unable to instantly move objects to 'collections' or folders is really difficult to organize my scene and instead have to drag it from the bottom of the list up to the top and scroll over 300 objects with a slow roll. 

https://www.youtube.com/watch?v=u_yIGGhubZs

**Comment by PlasmaDev5** [comment]
The issue is all relation have meaning in a hierarchy based system. Ideally developers would maintain a logical scene relation and organisation
