### ISSUE TITLE
Request: Automatically put new assets from the content browser into an existing group

### ISSUE THREAD

**Issue by Pat-a-wan** [PlasmaEngine/PlasmaEngine#114]
In Blender when creating a new asset it is automatically put into the master scene collection but users can select a group/collection and new assets will begin to be assigned automatically to that group/collection. 

It's a very handy feature when working with a lot of assets!

**Comment by PlasmaDev5** [comment]
I don't think this behaviour makes sense in a game engine as it's hierarchy based being a child has meaning and effects scene relation
