### ISSUE TITLE
Heightmaps don't save

### ISSUE THREAD

**Issue by Samuel2213** [PlasmaEngine/PlasmaEngine#12]
Heightmaps get yeeted when you close the engine

**Comment by DaveTheGameDev** [comment]
So it is "saving" but it appears the data is corrupted at some point and the data gets set to null.

![image](https://user-images.githubusercontent.com/21057342/103474795-7a5d5880-4dfb-11eb-9457-e177e36b76a9.png)

![image](https://user-images.githubusercontent.com/21057342/103474793-716c8700-4dfb-11eb-830c-c46ac34b1422.png)

**Comment by dragonCASTjosh** [comment]
Fixed in 0.1.3
