### ISSUE TITLE
Plasma incorrectly reading either normal maps or vertex normals

### ISSUE THREAD

**Issue by Samuel2213** [PlasmaEngine/PlasmaEngine#44]
Plasma is incorrectly reading either one of these, causing normal errors on models

How it should look
![image](https://user-images.githubusercontent.com/7733479/104708605-d9ad5800-576d-11eb-8c57-902195ff2b64.png)
Errors in Plasma
![image](https://user-images.githubusercontent.com/7733479/104708664-e8940a80-576d-11eb-8182-c4d6af57ad97.png)

How it should look
![image](https://user-images.githubusercontent.com/7733479/104708722-f8135380-576d-11eb-9526-93dea05a49ed.png)
Errors in Plasma
![image](https://user-images.githubusercontent.com/7733479/104708751-019cbb80-576e-11eb-9c66-bdcb8a56504f.png)

**Comment by dragonCASTjosh** [comment]
I believe this is now fixed
