### ISSUE TITLE
SpriteText does not render

### ISSUE THREAD

**Issue by UncannyMisc** [PlasmaEngine/PlasmaEngine#57]
steps to reproduce:

1. create a uiLevel
2. right click on one of the sprites in the object window and select create sprite text
3. try changing text to different values and font sizes

**Comment by UncannyMisc** [comment]
further investigation:
- the default material does not render the text, debug draw and debug draw ontop however does
- the default pixels per unit make the text extremely small compared to the default size for a newly created uilevel

**Comment by dragonCASTjosh** [comment]
This issue is unclear can you provide a photo or video of the error

**Comment by UncannyMisc** [comment]
The orange spec is a newly added sprite text
![sprite text selected](https://user-images.githubusercontent.com/45449920/112741834-ad675080-8fd4-11eb-91a5-2e907bce6b4b.PNG)
Here they are scaled up by 100 with a comparison between the default alphaSprite material and debug draw
![sprite text scaled - material comparison](https://user-images.githubusercontent.com/45449920/112741832-a8a29c80-8fd4-11eb-96a2-3e35aae0a503.PNG)

The issue is mainly a default values one where it makes them difficult to have to reset the size and material for each new one

**Comment by dragonCASTjosh** [comment]
Unable to replicate on my side

**Comment by dragonCASTjosh** [comment]
oh i see the issue your trying use pure Sprite Text, Currently that on its own is not intended for UI use. You should be using the text archetype from the UIWidget library. Ill be changing this behaviour at some point to ensure its use is clear
