### ISSUE TITLE
Imported Prefab does not have default tag applied

### ISSUE THREAD

**Issue by UncannyMisc** [PlasmaEngine/PlasmaEngine#63]
Something I noticed when importing a prefab, specifically the FPSController prefab I was handed (now outdated), when imported, some default tags do not get applied, such as "Cog" while when I go through and recreate it from scratch it is applied.
Might be an edge case of not handling the default tags correctly or just a difference in build versions between the prefab and the project version I am currently updated to (0.1.4.0
![FromScratch](https://user-images.githubusercontent.com/45449920/107496851-f494b000-6be5-11eb-81cf-2c0f8cadb0d6.png)
![Imported](https://user-images.githubusercontent.com/45449920/107496856-f5c5dd00-6be5-11eb-8c59-9df07f674960.png)
![HaloCharacterPack](https://cdn.discordapp.com/attachments/748756275038519348/804909883660173333/HaloController.plasmapack)
)

**Comment by dragonCASTjosh** [comment]
The COG tag is nolonger required and in many cases is in the process of removal
