### ISSUE TITLE
Persistant object visibility deletes script references in current editor instance?

### ISSUE THREAD

**Issue by UncannyMisc** [PlasmaEngine/PlasmaEngine#83]
Toggling a Persistent object (level settings, etc) on a new project then saving by using the top left button opens up the directional light script, complains that two scripts now no longer exist despite saving fine earlier and locks the editor in read only mode.

Since it enters read only mode it also doesn't transfer this state beyond the currently open editor instance and is fine once the project is closed and re-opened.

![image](https://user-images.githubusercontent.com/45449920/119602070-bc7c4a80-be2d-11eb-9dd2-ea5daf007018.png)

does not occur if the "persistent" objects are left alone before saving, which is difficult since they are in amongst the normal objects in the object window.

**Comment by UncannyMisc** [comment]
More information I just found out, the editor will not let you quit without saving in this state, nor will it let you quit with saving the changes due to the "read only" state.

**Comment by dragonCASTjosh** [comment]
@UncannyMisc looking at the screenshot your in the wrong build to use the renamed components, SSAO and Bloom was renamed in 0.1.6.0 to have the unified PostProcess prefix. Based on missing toolbar icons it looks like your using 0.1.5.0

**Comment by UncannyMisc** [comment]
just tried re-installing the build and it seems to have the correct buttons for debugging now, not sure why the launcher was launching a build other than the one I had selected, pretty much fixed on my side now
