### ISSUE TITLE
broken viewport movement when certain button key combos are used

### ISSUE THREAD

**Issue by MDPastor** [PlasmaEngine/PlasmaEngine#85]
pressing alt and dragging the scene with middle mouse button breaks viewport camera movement.

idk anything else because i'm engine ignorant

![image](https://user-images.githubusercontent.com/77067536/122946018-ec593800-d370-11eb-8fc9-5e7c34bd12a9.png)
selecting this back to zplane fixes it.

**Comment by PlasmaDev5** [comment]
@MDPastor can you provide more info on this. A video would be very useful
