### ISSUE TITLE
Particle system not working after pulling new changes

### ISSUE THREAD

**Issue by ZealOfApproval** [PlasmaEngine/PlasmaEngine#87]
I made a particle system in plasma of confetti, it was working well before I pulled new changes. After I pulled the new changes it won't emit the particles even when I press the "ResetCount" button in the particle emitter.

**Comment by dragonCASTjosh** [comment]
Linked to twister component, once twister is removed behavior is normal

**Comment by dragonCASTjosh** [comment]
I need more information to replicate this issue
